# Generated by Django 3.2.8 on 2021-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('last_play', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
